# Generated by Django 4.2.4 on 2023-08-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='ip',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='آی پی کاربر'),
        ),
    ]
