# Generated by Django 4.2.4 on 2023-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productcomment_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کامنت\u200cگذار'),
        ),
    ]
