# Generated by Django 4.2.4 on 2023-08-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
        ('product_module', '0007_remove_productreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_rating',
            field=models.IntegerField(default=1, verbose_name='تعداد امتیازدهندگان'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_module.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='product_color_categories', to='product_module.productcolorcategory', verbose_name='رنگ ها'),
        ),
    ]
